### ISSUE TITLE
问题有点多啊...

### ISSUE THREAD

**Issue by lndj** [Aoiujz/WechatSDK#2]
随便测试了下，比如那个WechatAuth userInfo接口没有带access_token，http方法写成https  用的时候又是http。。。正在使用中，有问题再反馈...

**Comment by lndj** [comment]
还有一点疑惑...勿怪..实例化WechatAuth类的时候，那个access_token哪里来,..不是实例化之后才获取的么

**Comment by Aoiujz** [comment]
第一个问题， userInfo是带了 access_token的啊， 你在哪里看到没带？ 还有，http方法你在哪里看到携程https了？
第二个问题，有access_token的时候直接传入，就不用在重新获取了啊， 你获取到的access_token是有有效期的，在有效期内直接传入就可以了，明白？
